# Generated by Django 6.0.6 on 2026-07-18 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplinas', '0001_initial'),
        ('turmas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('url', models.URLField(verbose_name='URL do Vídeo (YouTube/Vimeo)')),
                ('categoria', models.CharField(choices=[('aula', 'Aula'), ('tutorial', 'Tutorial'), ('palestra', 'Palestra'), ('documentario', 'Documentário'), ('animacao', 'Animação Educacional'), ('outro', 'Outro')], default='aula', max_length=20, verbose_name='Categoria')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='disciplinas.disciplina', verbose_name='Disciplina')),
                ('turmas', models.ManyToManyField(blank=True, related_name='videos', to='turmas.turma', verbose_name='Turmas')),
            ],
            options={
                'verbose_name': 'Vídeo',
                'verbose_name_plural': 'Vídeos',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
    ]
