# Generated by Django 6.0.5 on 2026-05-31 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Responsavel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("mae", "Mãe"),
                            ("pai", "Pai"),
                            ("avo_materno", "Avô Materno"),
                            ("ava_materna", "Avó Materna"),
                            ("avo_paterno", "Avô Paterno"),
                            ("ava_paterna", "Avó Paterna"),
                            ("tio", "Tio(a)"),
                            ("irmao", "Irmão(ã)"),
                            ("tutor", "Tutor(a)"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Parentesco",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(max_length=200, verbose_name="Nome Completo"),
                ),
                ("cpf", models.CharField(max_length=14, verbose_name="CPF")),
                ("telefone", models.CharField(max_length=20, verbose_name="Telefone")),
                (
                    "email",
                    models.CharField(blank=True, max_length=200, verbose_name="E-mail"),
                ),
                ("endereco", models.TextField(verbose_name="Endereço Completo")),
                (
                    "profissao",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Profissão"
                    ),
                ),
                (
                    "local_trabalho",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Local de Trabalho"
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
            ],
            options={
                "verbose_name": "Responsável",
                "verbose_name_plural": "Responsáveis",
                "ordering": ["nome_completo"],
            },
        ),
        migrations.AlterField(
            model_name="aluno",
            name="responsavel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alunos",
                to="alunos.responsavel",
                verbose_name="Responsável",
            ),
        ),
    ]
