# Generated by Django 6.0.5 on 2026-05-31 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("turmas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                ("data_inicio", models.DateTimeField(verbose_name="Data/Hora Início")),
                ("data_fim", models.DateTimeField(verbose_name="Data/Hora Fim")),
                (
                    "local",
                    models.CharField(blank=True, max_length=200, verbose_name="Local"),
                ),
                (
                    "cor",
                    models.CharField(
                        default="#007bff", max_length=7, verbose_name="Cor"
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
                (
                    "turmas",
                    models.ManyToManyField(
                        blank=True, related_name="eventos", to="turmas.turma"
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["data_inicio"],
            },
        ),
    ]
