# Generated by Django 6.0.5 on 2026-05-31 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alunos", "0001_initial"),
        ("turmas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Frequencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Presente"),
                            ("F", "Ausente"),
                            ("J", "Justificado"),
                            ("A", "Atrasado"),
                        ],
                        max_length=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "justificativa",
                    models.TextField(blank=True, verbose_name="Justificativa"),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frequencias",
                        to="alunos.aluno",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="frequencias_registradas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frequencias",
                        to="turmas.turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Frequência",
                "verbose_name_plural": "Frequências",
                "ordering": ["-data", "aluno"],
                "unique_together": {("aluno", "turma", "data")},
            },
        ),
    ]
