# Generated by Django 6.0.5 on 2026-05-31 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alunos", "0001_initial"),
        ("disciplinas", "0001_initial"),
        ("turmas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "bimestre",
                    models.IntegerField(
                        choices=[
                            (1, "1º Bimestre"),
                            (2, "2º Bimestre"),
                            (3, "3º Bimestre"),
                            (4, "4º Bimestre"),
                        ],
                        verbose_name="Bimestre",
                    ),
                ),
                (
                    "tipo_avaliacao",
                    models.CharField(
                        choices=[
                            ("prova", "Prova"),
                            ("trabalho", "Trabalho"),
                            ("atividade", "Atividade"),
                            ("participacao", "Participação"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Avaliação",
                    ),
                ),
                (
                    "nota",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Nota"
                    ),
                ),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=2, default=1.0, max_digits=5, verbose_name="Peso"
                    ),
                ),
                ("data_avaliacao", models.DateField(verbose_name="Data da Avaliação")),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="alunos.aluno",
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="disciplinas.disciplina",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="turmas.turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota",
                "verbose_name_plural": "Notas",
                "ordering": ["aluno", "disciplina", "bimestre"],
            },
        ),
    ]
