# Generated by Django 6.0.5 on 2026-05-31 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alunos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("fundamental1", "Fundamental I"),
                            ("fundamental2", "Fundamental II"),
                            ("medio", "Médio"),
                        ],
                        max_length=20,
                        verbose_name="Nível",
                    ),
                ),
                ("serie", models.IntegerField(verbose_name="Série")),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("manha", "Manhã"),
                            ("tarde", "Tarde"),
                            ("noite", "Noite"),
                        ],
                        max_length=10,
                        verbose_name="Turno",
                    ),
                ),
                ("ano_letivo", models.IntegerField(verbose_name="Ano Letivo")),
                (
                    "capacidade",
                    models.IntegerField(default=40, verbose_name="Capacidade"),
                ),
                (
                    "sala",
                    models.CharField(blank=True, max_length=20, verbose_name="Sala"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativa")),
            ],
            options={
                "verbose_name": "Turma",
                "verbose_name_plural": "Turmas",
                "ordering": ["ano_letivo", "nivel", "serie", "turno"],
            },
        ),
        migrations.CreateModel(
            name="TurmaAluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_matricula", models.DateField(auto_now_add=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turmaaluno",
                        to="alunos.aluno",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turmaaluno",
                        to="turmas.turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matrícula",
                "verbose_name_plural": "Matrículas",
                "unique_together": {("turma", "aluno")},
            },
        ),
    ]
