# Generated by Django 6.0.5 on 2026-05-31 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("professores", "0001_initial"),
        ("turmas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "carga_horaria",
                    models.IntegerField(verbose_name="Carga Horária (horas)"),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "obrigatoria",
                    models.BooleanField(default=True, verbose_name="Obrigatória"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativa")),
            ],
            options={
                "verbose_name": "Disciplina",
                "verbose_name_plural": "Disciplinas",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="DisciplinaTurma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disciplinaturma",
                        to="disciplinas.disciplina",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disciplinaturma",
                        to="professores.professor",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disciplinaturma",
                        to="turmas.turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disciplina da Turma",
                "verbose_name_plural": "Disciplinas das Turmas",
                "unique_together": {("disciplina", "turma")},
            },
        ),
    ]
